struct MixedMsg // msg 约400Byte
{
    short msg_priority; // 消息的优先级
    unsigned long long msg_sequence_num; // 消息序列号
    string msg_type; // 消息类型
    long msg_start_seconds; // 消息生成时间
    unsigned long msg_start_nanosec;
    long msg_end_seconds; // 消息结束时间
    unsigned long msg_end_nanosec;
    long msg_trans_time; // 消息已传输时间
    boolean is_overtime; // 是否超时
    char message[300]; // 携带的消息数据
};